### ISSUE TITLE
Wiki404

### ISSUE THREAD

**Issue by RCOdev** [pierotofy/glassomium#8]
Hello,
I'm interesting in testing glassomium, but the wiki is not alive anymore (http://www.glassomium.org/wiki/), is there any way to access this wiki, or another place where I can find information for compile and develop with glassomium?
thanks a lot!

**Comment by pierotofy** [comment]
Thanks for reporting the problem! I forgot to move the wiki when I changed hosting.

The wiki is now live again at http://glassomium.org/wiki/.

Thanks!

**Comment by RCOdev** [comment]
Yeah! Perfect, Thanks!
